.rubocop.yml, app/models/checkout.rb, app/models/concerns/bib_record.rb, app/models/hold.rb, app/models/patron.rb, app/views/summaries/_summary.html.erb, app/views/summaries/index.html.erb, spec/models/checkout_spec.rb, spec/models/hold_spec.rb, spec/models/patron_spec.rb, spec/models/user_spec.rb
Part of Issue #1 
* Added model specs for user and patron as part of #19
=> initial account overview work

app/services/symphony_client.rb, config/settings/test.yml, spec/rails_helper.rb, spec/services/symphony_client_spec.rb
=> Moar sws specs

app/services/symphony_client.rb, config/settings/test.yml, spec/rails_helper.rb, spec/services/symphony_client_spec.rb
=> SymphonyClient specs

app/controllers/application_controller.rb, app/controllers/summaries_controller.rb, app/models/patron.rb, spec/controllers/summaries_controller_spec.rb, spec/models/patron_spec.rb
@cdmo wondering what you would think about these changes? 
related to #24
=> Renew session refactor

app/mailers/application_mailer.rb, app/models/fine.rb, app/models/patron.rb, app/views/summaries/_summary.html.erb, spec/models/fine_spec.rb, spec/models/patron_spec.rb
#1 
Notes:
* didn't think we should reach into the Fines class during testing of Patron
* would like to refactor to extract "Sirsi System Items" into a class and take out things like key
* need to create view specs (what's in the View is demo purposes anyway)
Removes mailers
=> Fines summary

app/views/layouts/application.html.erb, app/views/shared/_user_util_links.html.erb, config/locales/en.yml
=> additional links - needs styling

Gemfile, Gemfile.lock, app/models/patron.rb, app/views/summaries/_summary.html.erb, spec/models/patron_spec.rb, spec/views/summaries/index.html.erb_spec.rb
part of Issue #1 - adding patron alerts to summary page
=> account overview alerts

app/views/holds/_holds_not_ready_table.html.erb, app/views/holds/_holds_ready_table.html.erb, app/views/holds/index.html.erb, spec/views/holds/index.html.erb_spec.rb
=> Adds conditional displays for holds

app/controllers/holds_controller.rb, config/locales/en.yml, spec/controllers/holds_controller_spec.rb
=> Updates hold cancelation success message to include call number.

app/components/bib_item_component.html.erb, app/components/bib_item_component.rb, spec/components/bib_item_component_spec.rb
#70 
actionview components made this pretty easy :)
=> Adds logic to not create a link if an item is from PALCI

app/services/symphony_client.rb
Refactor mentioned by @banukutlu in Slack
=> Removes unnecessary variable declaration

app/controllers/renewals_controller.rb, app/models/concerns/bib_record.rb, app/models/hold.rb, app/services/symphony_client.rb, app/views/checkouts/index.html.erb, spec/controllers/checkouts_controller_spec.rb, spec/controllers/fines_controller_spec.rb, spec/controllers/renewals_controller_spec.rb, spec/services/symphony_client_spec.rb
Issue #69 
Refactoring to use bib_summary, added Rails.logger for failed renewals, handled an error when no items selected to renew
=> 69 renewals error msgs

app/helpers/checkouts_helper.rb, config/locales/en.yml, spec/helpers/checkouts_helper_spec.rb, spec/views/checkouts/index.html.erb_spec.rb
=> hide due date time

app/models/patron.rb, app/views/summaries/_summary.html.erb, spec/models/patron_spec.rb, spec/views/summaries/index.html.erb_spec.rb
=> adding patron standing COLLECTION alert to summary

app/components/dashboard_item_component.html.erb, app/components/dashboard_item_component.rb
as per https://github.com/psu-libraries/myaccount/pull/89#discussion_r372585429
=> Swaps attr_reader for called instance vars.

config/locales/en.yml
see https://github.com/psu-libraries/myaccount/issues/5#issuecomment-580351231
=> Language update for errors in hold actions

app/components/select_all_child_component.html.erb, app/components/select_all_child_component.rb, app/components/select_all_component.html.erb, app/components/select_all_component.rb, app/helpers/checkouts_helper.rb, app/helpers/holds_helper.rb, app/javascript/select_all/index.js, app/views/checkouts/index.html.erb, app/views/holds/_holds_not_ready_table.html.erb, app/views/holds/_holds_ready_table.html.erb, spec/components/select_all_child_component_spec.rb, spec/components/select_all_component_spec.rb, spec/helpers/checkouts_helper_spec.rb, spec/views/checkouts/index.html.erb_spec.rb
=> Select all component

app/components/bib_item_component.rb, spec/components/bib_item_component_spec.rb
Co-authored-by: "Maryam Kutchemeshgi" <mxk128@psu.edu>
For #4
=> Adds a test to whether or not a bib item component should render.

app/components/bib_item_component.html.erb, app/components/bib_item_component.rb
=> do not link to record with unpublic types

app/models/bib.rb, spec/models/bib_spec.rb
=> Adds a sort on holdables by naturalized volumetric (#108)

app/helpers/holds_helper.rb, app/views/holds/_form_inputs.html.erb, spec/helpers/holds_helper_spec.rb, spec/views/holds/new.html.erb_spec.rb
#110
#121 should be reviewed first.
=> 110 default pickup date

app/components/place_hold_checkbox_component.html.erb, app/controllers/holds_controller.rb, app/helpers/holds_helper.rb, app/views/holds/_form_inputs.html.erb, app/views/holds/_holds_not_ready_table.html.erb, app/views/holds/new.html.erb, spec/components/place_hold_checkbox_component_spec.rb, spec/controllers/holds_controller_spec.rb, spec/helpers/holds_helper_spec.rb, spec/rails_helper.rb, spec/views/holds/_form_inputs.html.erb_spec.rb, spec/views/holds/new.html.erb_spec.rb
#126
#121, #124, #125 should be reviewed first.
=> 126 frontend validation

spec/models/checkout_spec.rb, spec/models/fine_spec.rb
=> refactoring checkout and fine spec

.rubocop.yml, app/services/place_hold_form/builder.rb, spec/factories/bibs.rb, spec/services/place_hold_form/builder_spec.rb
Issue #112 
calling this "Group things" was a mistake, really it's about "flattening." 
Additional change: updated rubocop settings
=> 112 group things

app/models/hold.rb
=> renaming pickup location

.rubocop_todo.yml, app/controllers/holds_controller.rb, app/services/place_hold_results/builder.rb, app/services/symphony_client.rb, spec/controllers/holds_controller_spec.rb, spec/services/place_hold_results/builder_spec.rb, spec/services/symphony_client_spec.rb
Issue #151 
✔ #147 needs to be merged before this
=> Refactor place hold results

app/components/place_hold_error_component.rb, app/components/place_hold_success_component.rb, app/services/place_hold_results/builder.rb, app/views/holds/result.html.erb, spec/controllers/holds_controller_spec.rb, spec/services/place_hold_results/builder_spec.rb
=> place hold fix

package.json, yarn.lock
to address acorn and minimist vulnerabilities
=> upgrade eslint

app/controllers/holds_controller.rb, app/controllers/redis_jobs_controller.rb, app/javascript/packs/application.js, app/javascript/submission_handling/cancel_hold.js, app/javascript/submission_handling/change_pickup_by_date.js, app/javascript/submission_handling/change_pickup_library.js, app/javascript/submission_handling/polling.js, app/javascript/submission_handling/shared.js, app/jobs/cancel_hold_job.rb, app/jobs/change_pickup_by_date_job.rb, app/jobs/change_pickup_library_job.rb, app/services/symphony_client.rb, app/views/holds/_form_inputs.html.erb, app/views/holds/_holds_not_ready_table.html.erb, app/views/holds/_holds_ready_table.html.erb, config/routes.rb, package.json, spec/controllers/holds_controller_spec.rb, spec/features/holds_spec.rb, spec/jobs/cancel_hold_job_spec.rb, spec/jobs/change_pickup_by_date_job_spec.rb, spec/jobs/change_pickup_library_job_spec.rb, spec/rails_helper.rb, spec/services/symphony_client_spec.rb, spec/support/fake_symphony.rb, yarn.lock
#181 should be merged first, then I'll rebase pending that review
=> 186 delete holds

app/components/dashboard_item_component.rb, app/javascript/packs/styles/_ask_a_librarian.scss, app/javascript/packs/styles/index.scss, app/models/patron.rb, app/views/layouts/_head.html.erb, app/views/layouts/application.html.erb, app/views/summaries/_summary.html.erb, spec/features/ask_a_librarian_spec.rb
For #28 
Review after #216 
Additional changes: added some safe navigation operators that I discovered were needed during testing. The specs threw an error that methods were undefined.
=> 28 ask a librarian

README.md, app/views/layouts/_head.html.erb, config/settings.yml
This is a change I'd like to make as I'm working on deployment, to make it more flexible and easier to manage I think.
=> Allows for overriding any config gem set value by environment variable.

app/components/bib_item_component.rb, app/helpers/application_helper.rb, app/javascript/packs/styles/_header.scss, app/javascript/packs/styles/_mixins.scss, app/javascript/packs/styles/_utilities.scss, app/views/layouts/_navigation.html.erb, spec/helpers/application_helper_spec.rb
#221 
after #225 
Makes the menu equal width and heavily contrasted on active/hover
=> 221 menu styling

app/helpers/fines_helper.rb, app/models/fine.rb, app/views/fines/_fines_table.html.erb, app/views/summaries/_summary.html.erb, spec/models/fine_spec.rb, spec/views/fines/index.html.erb_spec.rb, spec/views/summaries/index.html.erb_spec.rb
Issue #228 
Added summary text for no materials and no bills accounts
=> customized title for bills with no associated item

app/services/place_hold_form/builder.rb
=> fix for new hold form, when no holdable locations found

Gemfile, Gemfile.lock, config/environments/production.rb
#239 
And this copied entirely from https://github.com/psu-libraries/psulib_blacklight/pull/616
=> Adds lograge

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, spec/controllers/sessions_controller_spec.rb
=> redirect to original request url

.erb-lint.yml, app/javascript/submission_handling/cancel_hold.js, app/javascript/submission_handling/change_pickup_by_date.js, app/javascript/submission_handling/change_pickup_library.js, app/javascript/submission_handling/renew_checkout.js, app/javascript/submission_handling/shared.js, app/jobs/application_job.rb, app/jobs/change_pickup_by_date_job.rb, app/jobs/change_pickup_library_job.rb, app/jobs/renew_checkout_job.rb, app/models/checkout.rb, app/views/checkouts/_checkouts_table.html.erb, app/views/holds/_holds_not_ready_table.html.erb, app/views/shared/_success_badge.html.erb, spec/features/checkouts_spec.rb, spec/features/holds_spec.rb, spec/jobs/renew_checkout_job_spec.rb, spec/models/checkout_spec.rb
for #255 
~this will need a rebase after #253~ rebased
=> 255 success notification

config/initializers/datadog.rb, config/settings/production.yml
=> Sets environment based on config gem setting for datadog

app/views/checkouts/index.html.erb, app/views/holds/index.html.erb, config/locales/en.yml
=> revised loading msg

app/javascript/packs/styles/_header.scss, app/javascript/packs/styles/_small_screen.scss, app/javascript/packs/styles/index.scss, app/javascript/submission_handling/shared.js, app/views/checkouts/_checkouts_table.html.erb, app/views/holds/_holds_not_ready_table.html.erb, app/views/holds/_holds_ready_table.html.erb, app/views/layouts/_navigation.html.erb, app/views/shared/_nav_link.html.erb
=> 217 frontend issues

app/models/fine.rb, app/services/symphony_client.rb, spec/factories/fines.rb, spec/models/fine_spec.rb, spec/views/fines/index.html.erb_spec.rb
=> bill reason from policy

app/controllers/holds_controller.rb, app/helpers/holds_helper.rb, app/jobs/view_holds_job.rb, app/models/hold.rb, app/services/place_hold_form/builder.rb, app/views/holds/_form_inputs.html.erb, app/views/holds/_holds_not_ready_table.html.erb, app/views/holds/all.html.erb, app/views/holds/new.html.erb, spec/helpers/holds_helper_spec.rb, spec/services/place_hold_form/builder_spec.rb, spec/views/holds/_form_inputs.html.erb_spec.rb
=> Adds the patron's library as the default selected option

app/javascript/submission_handling/cancel_hold.js, app/javascript/submission_handling/change_pickup_by_date.js, app/javascript/submission_handling/change_pickup_library.js, app/javascript/submission_handling/renew_checkout.js, app/javascript/submission_handling/shared.js, spec/features/checkouts_spec.rb, spec/features/holds_spec.rb
=> clear all badges

app/views/shared/_user_util_links.html.erb, config/locales/en.yml
Per convo with Binky, added prominent link to website feedback. Also changed the questions link to indicate it's an FAQ page not the place to ask questions.
=> Help links

.scss-lint.yml, app/components/dashboard_item_component.html.erb, app/javascript/packs/styles/_callouts.scss, app/javascript/packs/styles/index.scss, app/views/checkouts/index.html.erb, app/views/shared/_callout.html.erb, app/views/summaries/_summary.html.erb, config/locales/en.yml
#289 
Also makes the dashboard display at small screen a bit cleaner
=> Adds quarantine notice as a callout

app/javascript/submission_handling/cancel_hold.js, app/jobs/cancel_hold_job.rb, app/views/holds/_holds_ready_table.html.erb, spec/features/holds_spec.rb, spec/jobs/cancel_hold_job_spec.rb
#293 (fixed bad spelling of "Cancelled" too)
=> Hold cancel badge

app/helpers/holds_helper.rb, app/views/holds/_holds_not_ready_table.html.erb, app/views/holds/_holds_ready_table.html.erb, spec/helpers/holds_helper_spec.rb
=> Checks for null on fillByDate response for Hold

app/components/patron_field_component.html.erb, app/views/patrons/edit.html.erb, spec/views/patrons/edit.html.erb_spec.rb
=> Fixes smushing in smaller screens

app/views/checkouts/all.html.erb, app/views/holds/all.html.erb, config/locales/en.yml
#265  
Also removed some unused keys from en.yml
=> info message for checkouts and holds

app/views/holds/all.html.erb, config/locales/en.yml
https://github.com/psu-libraries/myaccount/issues/265#issuecomment-720498239
=> links to illiad and medianet

app/javascript/submission_handling/polling.js, spec/features/holds_spec.rb
#312 
This is probably not a good sol'n but the only one I could find, I am open to other ideas, wanna hear your thoughts @cdmo.
Also to note here, checking document.referrer did not work in this case because when back button is used, browser is serving from the cache and returns the original referrer.
=> attempt for a workaround to back button to holds/result issue

app/controllers/errors_controller.rb, app/models/patron.rb, app/views/holds/all.html.erb, app/views/layouts/_navigation.html.erb, app/views/layouts/application.html.erb, spec/features/ask_a_librarian_spec.rb, spec/features/checkouts_spec.rb, spec/features/fines_spec.rb, spec/features/holds_spec.rb, spec/features/patron_spec.rb, spec/features/summaries_spec.rb, spec/requests/errors_spec.rb, spec/views/layouts/application.html.erb_spec.rb
=> 404s with formats other than html

README.md, app/javascript/packs/styles/_announcement.scss, app/javascript/packs/styles/index.scss, app/views/layouts/_announcement.html.erb, app/views/layouts/application.html.erb, config/settings.yml, spec/views/layouts/application.html.erb_spec.rb
=> adds an announcement bar

app/javascript/submission_handling/polling.js
attempting to fix the issue with page reloads on safari and edge
[INC1607440](https://pennstate.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=a9983601dbf9a4102c4f9e74f3961935%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)
=> adding array length check to navigationType

app/controllers/holds_controller.rb, app/javascript/submission_handling/change_pickup_by_date.js, app/views/holds/_form_inputs.html.erb
=> pickup date fixes for Safari

app/services/sirsi_response/error.rb, app/views/sirsi_response/error.html.erb
=> adding error code 238 to sirsi translation

app/controllers/application_controller.rb, config/initializers/warden.rb, spec/features/session_life_spec.rb
#334 When you have a minute @banukutlu can we talk about how to better organize this new session cookie management? Thinking about making this a separate Module, also thinking about testing.
=> Creates session life tracking cookies and actions

config/initializers/datadog.rb
=> two more sirsi response to exclude from dd

config/initializers/datadog.rb
=> one more dd exclude

app/services/place_hold_form/builder.rb, spec/services/place_hold_form/builder_spec.rb
=> fix to delete prefix from catkey for place holds coming from Summon

app/services/symphony_client.rb, config/settings/test.yml, spec/requests/errors_spec.rb, spec/services/symphony_client_spec.rb
@whereismyjetpack I've update the specs to get them to pass, when you get a chance, could you pls check these and if they are OK, maybe then we can merge to your branch.
=> login spec updates

app/javascript/submission_handling/change_pickup_by_date.js, app/javascript/submission_handling/change_pickup_library.js, spec/features/holds_spec.rb
=> Uncheck boxes when holds are edited by the user

app/javascript/submission_handling/cancel_hold.js, spec/features/holds_spec.rb
=> Uncheck boxes when the user cancels a hold

.circleci/config.yml
- created an org-global context in circle ci that has "defaulty" values for things like CI_IMAGE_UTILS_IMG_TAG, etc. we're updating the ci-utils image tag to work with the new version of harbor
=> updates CI config

config/settings.yml
=> altoona pickup location change

spec/features/holds_spec.rb
Changing this spec to pending until we have a fix for it #423 so the CI works for releases. 
We reviewed the behavior that is being tested with this spec on QA, it seems to be working OK.
=> Failing flakey hold spec to pending

app/views/checkouts/all.html.erb, config/locales/en.yml
=> Add message about returning to Checkouts/Renewals page

app/views/holds/_form_inputs.html.erb
=> Update hold date text on hold form and make it larger/italic

.circleci/config.yml, Dockerfile, Gemfile.lock, babel.config.js, bin/webpack, bin/webpack-dev-server, config/webpack/environment.js, config/webpacker.yml, package.json, yarn.lock
Updates Node / Webpacker 
fixes #518
=> updates node / webpacker

app/views/layouts/_head.html.erb
Closes #573 
Note: These changes needs to be deployed on 1/25 8-9am
=> Ask A Librarian updates

.rubocop.yml, app/controllers/application_controller.rb, app/controllers/holds_controller.rb, app/controllers/ill_controller.rb, config/locales/en.yml, spec/controllers/holds_controller_spec.rb, spec/controllers/ill_controller_spec.rb
=> check if user barred, if so flash error and redirect to summaries

app/views/ill/new.html.erb, spec/views/ill/new.html.erb_spec.rb
This is what this change looks like ☝️ .  Open to different ideas if anyone has any.
closes #574
=> Link to new non-ill hold from new ill hold form 

app/views/summaries/_summary.html.erb
dashboard was only rendering if someone had symphony materials
=> adds ILL holds and checkout to summaries dashboard conditional

app/components/ill_place_hold_checkbox_wrapper_component.html.erb, app/components/ill_place_hold_checkbox_wrapper_component.rb, app/services/illiad_client.rb, app/views/ill/new.html.erb, spec/components/ill_place_hold_checkbox_wrapper_component_spec.rb, spec/features/holds_spec.rb, spec/services/illiad_client_spec.rb
Fixes #613 
Also fixes flaky features/holds spec
=> sends call number instead of barcode for ILL volumetric requests

app/services/illiad_client.rb, spec/features/summaries_spec.rb, spec/services/illiad_client_spec.rb, spec/services/illiad_response_spec.rb
=> Adds 'Pattee Notices' to holds query

Gemfile, Gemfile.lock
Reverts psu-libraries/myaccount#624
sidekiq 7 has some breaking changes i overlooked.
=> Revert "Bump sidekiq from 6.4.2 to 7.0.8"

app/controllers/application_controller.rb, spec/controllers/holds_controller_spec.rb, spec/controllers/ill_controller_spec.rb
Closes #628 
note: would be good idea to refactor this later to move the barred check to patron class as a method like `barred?`
=> only barred standing

config/locales/en.yml, config/settings.yml
Fixes #627 
It seems like the new links are already working, so this can be merged/deployed
=> updates illiad urls

app/services/sirsi_response/error.rb, spec/services/sirsi_response/error_spec.rb
=> adds translation for acknowledgeRenewalFeeCircPrompt error

config/locales/en.yml
=> Changed mtss link

.circleci/config.yml, Gemfile, Gemfile.lock, config/routes.rb, docker-compose.yaml, spec/rails_helper.rb
Updates sidekiq. Simplecov needed updating at the same time, redis was also updated at this time
=> updates sidekiq, and simplecov, redis

app/controllers/redis_jobs_controller.rb
skipping token verification created a cross site request forgery vulnerability
This removes the line that skipped verification
=> resolves CSRF vulnerability

yarn.lock
Fixes #718 
Other vulnerabilities were fixed through dependabot
=> update jest to fix braces vulnerability

config/initializers/sidekiq.rb, config/settings.yml
- **configure sidekiq timeouts**
- **rubocop**
=> adds timeout options to sidekiq

config/settings.yml
add engineering library back with new address upon reopening
do not deploy until 8/26
=> add engineering library back

app/views/checkouts/_checkouts_table.html.erb, app/views/shared/_session_expiry_modal.html.erb
=> fixed broken aria references and empty table header
