app/controllers/application_controller.rb, app/controllers/summaries_controller.rb, app/models/patron.rb, config/settings/test.yml, spec/controllers/summaries_controller_spec.rb, spec/models/patron_spec.rb
#24 
I left the `#logout` on `SessionsController`. I figured we may actually want to keep it around either because we will present this to our users as an option for logging out OR for our own local dev purposes? Not sure.
Also, please do look for another way of doing this! I'm all ears.
Lastly, in order to simulate an invalid session you can throw a byebug/pry on `ApplicationController#current_user` and set a bad patronKey like 
`[1] pry(#<SessionsController>)> session_data['session_token'] = '83838'`
And that will invalidate the session.
Adds a comment on session/user management.
=> Renew session

.dependabot/config.yml
Just an experiment, see https://dependabot.com/docs/config-file/
You can tell dependabot to make PRs to update your dependencies. I set it to monthly so it wouldn't be overly annoying. IDK, what do you think?
=> Adds a dependabot watcher config

app/controllers/renewals_controller.rb, app/services/symphony_client.rb, spec/controllers/renewals_controller_spec.rb, spec/services/symphony_client_spec.rb
I was thinking that we could make the renewal response uniform so that we can reduce the complexity of the code in the controller. 
A step further to me would be to turn this uniform hash into a small class like SirsiRenewalResponse.
=> Refactored to make the renewal response from Sirsi uniform.

app/models/hold.rb
Didn't catch this earlier with our preset pickup libraries showing &amp; in the select to the user
=> &amp; to &

config/routes.rb
Otherwise accessing, for example `summaries/new` gives a misleading error.
=> Makes routes more specific, exact

app/components/generic_value_with_label_component.html.erb, app/components/generic_value_with_label_component.rb, app/views/holds/new.html.erb, spec/components/generic_value_with_label_component_spec.rb
This is my own idea, based on a small bug where we saw "Author: " and no value.
#121 and #124 should be reviewed first.
=> Generic actionview component

Gemfile, Gemfile.lock, README.md, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/settings.yml
a little too easy to setup. More to come soon
Relevant:
`activesupport-6.0.1/lib/active_support/cache/redis_cache_store.rb`
Added a "ubiquitous language" section (i.e., terminology)
=> redis for session (and cache)

app/services/symphony_client.rb
Very small change to the default patron info requested, because `address1` is only needed for the patron info page with the address on it, remove it from every request generically as it serves no purpose but adding a little weight.
=> Removes address1 from every request

.rubocop.yml, Procfile, app/controllers/redis_jobs_controller.rb, app/jobs/cancel_hold_job.rb, app/jobs/change_pickup_by_date_job.rb, app/jobs/change_pickup_library_job.rb, app/jobs/view_holds_job.rb, app/models/concerns/bib_record.rb, config/application.rb, config/initializers/redis.rb, config/initializers/sidekiq.rb, config/puma.rb, config/settings.yml, config/sidekiq.yml, spec/controllers/redis_jobs_controller_spec.rb, spec/jobs/cancel_hold_job_spec.rb, spec/jobs/change_pickup_by_date_job_spec.rb, spec/jobs/change_pickup_library_job_spec.rb, spec/jobs/view_holds_job_spec.rb
These changes allow for Heroku to work with Redis for everything we use Redis for: caching, Sidkiq and temporary "database"
Key change was making the "database" connection defined once as a global constant.
=> Sidekiq on heroku with redis

app/views/holds/new.html.erb
Without this the form for creating new holds *does not work*
=> Forces the Hold creation to be "local" (i.e., not "remote" - XHR)

spec/features/holds_spec.rb, spec/support/data/other/bib_6066288.json, spec/support/data/other/locations.json, spec/support/fake_symphony.rb
I also attempted to create a feature spec that shows a successful hold creation (that I didn't include in this PR of course), however it just redirects to example.com because it is trying reauthenticate when the redirect to holds/result happens. Not sure how to get around this, but it'd be nice to have a feature spec for successful hold creation too.
=> Adds feature spec for new hold form population

app/controllers/application_controller.rb, app/controllers/checkouts_controller.rb, app/controllers/holds_controller.rb, app/models/patron.rb, spec/features/checkouts_spec.rb, spec/features/holds_spec.rb
=> force checkouts and holds pages reload on browser back button

app/controllers/holds_controller.rb, app/models/bib.rb, app/models/new_hold_exception.rb, app/services/place_hold_form/builder.rb, config/locales/en.yml, spec/controllers/holds_controller_spec.rb, spec/factories/bibs.rb, spec/services/place_hold_form/builder_spec.rb
Issue #237, also fixes Issue #220
=>  fix for new hold form for non holdable records

yarn.lock
Just to remediate CVE-2020-7720 - not that it's a concern for us because this is dev only.
=> Yarn upgrade of webpack-dev-server to bump node-forge

app/lib/myaccount_version.rb, config/initializers/datadog.rb, spec/lib/myaccount_version_spec.rb
I noticed in prod logs that we are getting errors regarding rate limits, so caching for 5 minutes to avoid problems
=> Caches the version for 5 minutes and refactors class

config/settings.yml
overriding is at the key level not the array level
=> Removes UP College of Medicine pickup location

app/controllers/checkouts_controller.rb, app/javascript/submission_handling/cancel_hold.js, app/javascript/submission_handling/change_pickup_by_date.js, app/javascript/submission_handling/change_pickup_library.js, app/javascript/submission_handling/renew_checkout.js, app/jobs/renew_checkout_job.rb, app/views/layouts/application.html.erb, app/views/shared/_session_expiry_modal.html.erb, app/views/sirsi_response/error.html.erb, spec/features/bad_session.rb
#295 
Handles `422` server responses by quickly displaying a message that session is stale
I attempted a feature spec, tried a few variations on:
```rb
context 'when patron\'s session has become stale' do
it 'shows a modal telling the user to start a new session', js: true do
page.driver.browser.manage.delete_all_cookies
page.check 'renewal_list__2145643:5:1'
page.click_button 'Renew', match: :first
sleep 3
expect(page).to have_css '#expiryModal'
end
end
```
but not quite there. Might be impossible to test?
=> Adds an error condition and reaction for AJAX requests

app/controllers/holds_controller.rb, app/models/hold_exception.rb, spec/controllers/holds_controller_spec.rb
#288 
This is probably not a regular user case but just in case if somebody directly goes to `/holds/result`.
=> check referer on holds/result

app/helpers/holds_helper.rb, app/services/place_hold_form/builder.rb, spec/helpers/holds_helper_spec.rb
#274 
Additionally, a change to check filter_holdables even if there is only one holding - this only covers withdrawn records and such and users could not get to those records anyway but I think it does not hurt to change the check to cover it.
=> If default location is not in pickup locations list, add a blank option to force selection

app/views/patrons/edit.html.erb
#321 
see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-multiple
I was unable to figure out how to get Capybara to detect the little validation tooltips that pop up when you have entered something invalid
=> 321 multiple emails

Gemfile.lock
fix for https://app.datadoghq.com/apm/traces?end=1611684984852&paused=false&query=env%3Aproduction%20-status%3Aok&spanID=1726633474243818674&start=1611681384852&storage=hot&streamTraces=true&trace=AQAAAXc_y85ZxaFRoQAAAABBWGNfeTlHVEFBQ2g4elhCd2hlc3BkY1Q&traceID=1429882010751998963
See https://github.com/redis/redis-rb/issues/961
```
NoMethodError: undefined method `bytesize' for nil:NilClass
/data/websites/myaccount/vendor/bundle/ruby/2.6.0/gems/redis-4.2.3/lib/redis/connection/ruby.rb:86:in `block in _write_to_socket'
/data/websites/myaccount/vendor/bundle/ruby/2.6.0/gems/redis-4.2.3/lib/redis/connection/ruby.rb:72:in `loop'
/data/websites/myaccount/vendor/bundle/ruby/2.6.0/gems/redis-4.2.3/lib/redis/connection/ruby.rb:72:in `_write_to_socket' …
```
=> Upgrades redis gem, fix fatal error

config/initializers/datadog.rb
#358 
These response codes are expected and does not need to be reported as error since we do not act on them.
=> more sirsi response error codes to exclude from datadog

bin/test, docker-compose.yaml
The startup time for using `docker-compose run` IMO, was too high, so instead I set it up so that we `exec` right into the already running thing. this helps with things like sprig too if we're using that!
=> don't use profiles

.github/dependabot.yml
our base image runs updates on security updates, when an update is found dependabot will issue a PR for update.
=> adds dependabot config for docker

.envrc.example, docker-compose.yaml
allows the user to change the SYMWS_* variables in their local .envrc file. SYMWS_URL no longer defaults so it must be set in the .envrc file
=> parameterizes more of docker-compose config

app/javascript/submission_handling/cancel_hold.js, app/javascript/submission_handling/change_pickup_by_date.js, app/javascript/submission_handling/change_pickup_library.js, spec/features/holds_spec.rb
I have no idea why changing the timing of the uncheck logic makes any difference, but it does.
=> Fix hanging spinners when editing both location and pickup date

config/initializers/datadog.rb, config/settings/production.yml
in the config-repo we can set 
```
datadog:
enabled: [true|false]
```
when switched in the helm chart we set the env appropriately (preview, or production) and then we also set the host to the cluster apm collector
I renamed `on_server` to `enabled` to follow the naming we use elsewhere. I can go either way on that change.
=> allow datadog to be switched via ENV

app/views/errors/internal_server_error.html.erb
Closes #454.
Change the link to point to the libraries website feedback form instead of going to Qualtrics.
=> Update feedback link in internal server error page

.rubocop.yml, app/services/symphony_client.rb, config/initializers/okcomputer.rb, config/initializers/warden.rb, lib/healthchecks.rb, lib/healthchecks/symphony_check.rb, spec/services/symphony_client_spec.rb
1. breaks out login, and get_patron record
2. returns status, and auth token from `login` this allows us to bubble up errors
3. refactors warden to use this method 
4. makes get_patron_record a public method, too
5. adds /health/symphony endpoint 
I'm not 100% sold on how this is done, but the idea is if there are errors in the application we can look at the logs, or look at /health/symphony or /health/all to see any error message that might bubble up 
Fixes #472
=> adds symphony healthcheck

app/controllers/lending_policy_controller.rb, app/javascript/accept_lending_policy.js, app/javascript/packs/application.js, app/models/patron.rb, app/services/symphony_client.rb, app/views/lending_policy/show.html.erb, app/views/lending_policy/thank_you.html.erb, config/routes.rb, config/settings.yml, config/settings/test.yml, spec/controllers/lending_policy_controller_spec.rb, spec/features/lending_policy_spec.rb, spec/jobs/view_checkouts_job_spec.rb, spec/jobs/view_holds_job_spec.rb, spec/models/patron_spec.rb, spec/services/symphony_client_spec.rb, spec/support/data/patrons/patron1.json
Closes #484.
A new page has been added which allows a patron to accept the University Libraries' Lending Policy, which, if the user is eligible, opts them into wage garnishment.
Currently, only faculty and staff are eligible to opt into this agreement. Opting in sets the patron standing to `OK` and sets the `GARNISH-DT` (garnish date) to the current date.
If you want the override key for testing purposes, it is stored in Vault. Please let me know if you need access.
=> Add ability for patrons to opt into wage garnishment

app/views/summaries/_summary.html.erb, spec/views/summaries/index.html.erb_spec.rb
Closes #490.
For barred patrons who are eligible to opt into wage garnishment, we now show a link in the "Alerts" section to the lending policy so they can accept it and "unbar" their account.
=> Summary Page: add link to accept lending policy for eligible patrons

app/jobs/place_holds_job.rb, app/models/patron.rb, app/views/holds/_results.html.erb, spec/features/holds_spec.rb, spec/support/data/other/barcode_000080913573.json, spec/support/data/other/bib_24053587.json, spec/support/data/other/symphony_error.json, spec/support/data/patrons/patron3.json, spec/support/fake_symphony.rb
Display link to accept lending policy when patron's are barred because they have not yet accepted the policy.
Fixes #493 
Due to the way FakeSymphony is set up, I had to create a number of support files in order to create the 500 response. If there is a more efficient way around this, I'd be happy to learn & then refactor. Just let me know!
=> unbar link

app/components/place_hold_date_component.rb, app/views/holds/_form_inputs.html.erb, app/views/holds/_holds_not_ready_table.html.erb, app/views/holds/new.html.erb, app/views/ill/new.html.erb, spec/views/holds/_form_inputs.html.erb_spec.rb, spec/views/ill/new.html.erb_spec.rb
Fixes #571 
For ILL holds, default not needed after date extended to 45 days, and accept ebook and accept alternate edition are now unchecked by default.
=> change ILL hold defaults

app/views/holds/_results.html.erb, app/views/ill/_results.html.erb, config/locales/en.yml, spec/views/ill/result.html.erb_spec.rb
Refactored 'See all holds' text into translation ymls.  Changed the ill results 'See all __' button to say 'See all holds'.
I couldn't get this page to load locally to double check that this works.  The tests pass, though.
=> 'See all holds' button for Ill requests

.rubocop.yml, app/controllers/ill_controller.rb, app/controllers/summaries_controller.rb, app/services/illiad_response.rb, app/services/symphony_client_parser.rb, app/views/summaries/_summary.html.erb, app/views/summaries/index.html.erb, spec/controllers/summaries_controller_spec.rb, spec/features/ask_a_librarian_spec.rb, spec/features/session_life_spec.rb, spec/features/summaries_spec.rb, spec/services/illiad_response_spec.rb, spec/views/summaries/index.html.erb_spec.rb
Fixes #572 
Also fixes ILL hold bug: With Ruby 3 upgrade, positional vs keyword arguments were separated. This caused some errors with the SymphonyClientParser that were resolved.
=> add ILLiad materials to summary counts

app/services/symphony_client.rb, app/views/holds/new.html.erb, spec/views/holds/new.html.erb_spec.rb
Fixes #578 
I spoke with Ruth & we're extending this to any patrons who are not eligible for ILL, not just PA residents.
Patrons who are not ILL eligible will see the following message:
=> suggest local library for ILL ineligible

spec/rails_helper.rb
webdriver 115 is at a different location, webdriver gem has yet to be updated to pull from that location.
=> pins webdriver

.rubocop.yml, app/views/summaries/_summary.html.erb, spec/views/summaries/index.html.erb_spec.rb
Adds text and link to ILLiad on summaries page when no ILL items.  Tests for this.
closes #641
=> Link to ILLiad when no ILL items

app/controllers/redis_jobs_controller.rb
Reverts psu-libraries/myaccount#684
we appear to be seeing in our logs errors that indicates this PR was the cause. 
We should revert this as a hot fix, and investigate the issue a bit further.
=> Revert "resolves CSRF vulnerability"

config/initializers/bugsnag.rb
https://github.com/sidekiq/sidekiq/issues/4560
sidekiq uses the APP_ENV variable to mean the sidekiq app env, and overrides rails_env if set.
=> rename app_env variable

config/settings.yml
removes them from the pickup location dropdown
=> remove engineering library while they are temporarily closed
